version: '3.4'
x-environment:
    &common-variables
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: db_name

services:
    jtech_magento1_web:
        build:
            context: .
            target: web
        ports:
            - "80:80"
        volumes:
            - ../:/var/www/html/
        links:
            - jtech_magento1_db:db
        depends_on:
            - jtech_magento1_db
        environment: *common-variables
    jtech_magento1_db:
        build:
            context: .
            target: db
        environment: *common-variables
        ports:
            - "3306:3306"
        volumes:
            - magento-db-data:/var/lib/mysql/data

volumes:
    magento-db-data: