version: '3.4'
services:
    jtech_magento1_web:
        container_name: jtech_magento1_web
        build:
            context: php-apache
            target: web
        ports:
            - "80:80"
        volumes:
            - ../:/var/www/html/
        links:
            - jtech_magento1_db:db
        depends_on:
            - jtech_magento1_db
        environment:
          - APACHE_RUN_USER=#1000
          - APACHE_RUN_GROUP=#1000

    jtech_magento1_db:
        container_name: jtech_magento1_db
        build:
            context: mysql
            target: db
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - magento-db-data:/var/lib/mysql

volumes:
    magento-db-data: